package uabc.miclimafavorito.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006629)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF008236)
val onPrimaryContainerLight = Color(0xFFDBFFD9)
val secondaryLight = Color(0xFF81008D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA800B7)
val onSecondaryContainerLight = Color(0xFFFFCCFA)
val tertiaryLight = Color(0xFF005082)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF0069A8)
val onTertiaryContainerLight = Color(0xFFD0E5FF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF5FBF1)
val onBackgroundLight = Color(0xFF171D17)
val surfaceLight = Color(0xFFF5FBF1)
val onSurfaceLight = Color(0xFF171D17)
val surfaceVariantLight = Color(0xFFDAE6D6)
val onSurfaceVariantLight = Color(0xFF3F4A3E)
val outlineLight = Color(0xFF6E7A6D)
val outlineVariantLight = Color(0xFFBECABA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322B)
val inverseOnSurfaceLight = Color(0xFFEDF3E8)
val inversePrimaryLight = Color(0xFF72DC84)
val surfaceDimLight = Color(0xFFD6DCD2)
val surfaceBrightLight = Color(0xFFF5FBF1)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5EB)
val surfaceContainerLight = Color(0xFFEAF0E5)
val surfaceContainerHighLight = Color(0xFFE4EAE0)
val surfaceContainerHighestLight = Color(0xFFDEE4DA)



val primaryDark = Color(0xFF72DC84)
val onPrimaryDark = Color(0xFF003914)
val primaryContainerDark = Color(0xFF008236)
val onPrimaryContainerDark = Color(0xFFDBFFD9)
val secondaryDark = Color(0xFFFFA9FE)
val onSecondaryDark = Color(0xFF590061)
val secondaryContainerDark = Color(0xFFA800B7)
val onSecondaryContainerDark = Color(0xFFFFCCFA)
val tertiaryDark = Color(0xFF99CBFF)
val onTertiaryDark = Color(0xFF003355)
val tertiaryContainerDark = Color(0xFF0069A8)
val onTertiaryContainerDark = Color(0xFFD0E5FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F150F)
val onBackgroundDark = Color(0xFFDEE4DA)
val surfaceDark = Color(0xFF0F150F)
val onSurfaceDark = Color(0xFFDEE4DA)
val surfaceVariantDark = Color(0xFF3F4A3E)
val onSurfaceVariantDark = Color(0xFFBECABA)
val outlineDark = Color(0xFF889486)
val outlineVariantDark = Color(0xFF3F4A3E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DA)
val inverseOnSurfaceDark = Color(0xFF2C322B)
val inversePrimaryDark = Color(0xFF006E2C)
val surfaceDimDark = Color(0xFF0F150F)
val surfaceBrightDark = Color(0xFF353B34)
val surfaceContainerLowestDark = Color(0xFF0A100A)
val surfaceContainerLowDark = Color(0xFF171D17)
val surfaceContainerDark = Color(0xFF1B211B)
val surfaceContainerHighDark = Color(0xFF252C25)
val surfaceContainerHighestDark = Color(0xFF30362F)


val dayLight                = Color(0xFF006878)
val onDayLight              = Color(0xFFFFFFFF)
val dayContainerLight       = Color(0xFFA7EEFF)
val onDayContainerLight     = Color(0xFF004E5B)

val dayDark                 = Color(0xFF83D2E5)
val onDayDark               = Color(0xFF00363F)
val dayContainerDark        = Color(0xFF004E5B)
val onDayContainerDark      = Color(0xFFA7EEFF)


val nightLight              = Color(0xFF5A5891)
val onNightLight            = Color(0xFFFFFFFF)
val nightContainerLight     = Color(0xFFE3DFFF)
val onNightContainerLight   = Color(0xFF424078)

val nightDark               = Color(0xFFC3C0FF)
val onNightDark             = Color(0xFF2C2960)
val nightContainerDark      = Color(0xFF424078)
val onNightContainerDark    = Color(0xFFE3DFFF)
